### ISSUE TITLE
Build failure with OpenSSL 4.0

### ISSUE THREAD

**Issue by raviksharma** [savoirfairelinux/opendht#870]
This bug was filed using automation as part of the Debian OpenSSL 4.0 migration effort. Please ignore if the build issue is already fixed.

More details and build logs in the Debian bug report:
https://bugs.debian.org/1138404

**Comment by aberaud** [comment]
@bandali I believe this is fixed in recent versions of OpenDHT ^

**Comment by loqs** [comment]
@aberaud as of https://github.com/savoirfairelinux/opendht/commit/699073acd8fa0d20cd420c588a14b720f8bb63b9 opendht still fails to build with OpenSSL 4.0 although the error is different:
```
/opendht/src/http.cpp: In function ‘X509* dht::http::issuer_from_chain(stack_st_X509*)’:
/opendht/src/http.cpp:308:44: error: invalid conversion from ‘const X509_NAME*’ {aka ‘const X509_name_st*’} to ‘X509_NAME*’ {aka ‘X509_name_st*’} [-fpermissive]
  308 |     if ((issuer_name = X509_get_issuer_name(cert)) == nullptr)
      |                        ~~~~~~~~~~~~~~~~~~~~^~~~~~
      |                                            |
      |                                            const X509_NAME* {aka const X509_name_st*}
```
Which an be fixed by adding the const:
```patch
--- a/src/http.cpp
+++ b/src/http.cpp
@@ -302,7 +302,7 @@ static X509*
 issuer_from_chain(STACK_OF(X509) * fullchain)
 {
     X509 *cert, *issuer;
-    X509_NAME* issuer_name;
+    const X509_NAME* issuer_name;
 
     cert = cert_from_chain(fullchain);
     if ((issuer_name = X509_get_issuer_name(cert)) == nullptr)

```

**Comment by aberaud** [comment]
Fixed in v4.2.1

**Comment by loqs** [comment]
Confirming v4.2.1 build with OpenSSL 4.0.0 without issue.
