### ISSUE TITLE
Fails to build with restinio-0.7.2

### ISSUE THREAD

**Issue by yurivict** [savoirfairelinux/opendht#702]
```
In file included from /wrkdirs/usr/ports/devel/opendht/work/opendht-3.1.11/src/dht_proxy_client.cpp:26:
/usr/local/include/http_parser.h:157:19: error: redefinition of enumerator 'HTTP_STATUS_CONTINUE'
  HTTP_STATUS_MAP(XX)
                  ^
/usr/local/include/llhttp.h:190:3: note: previous definition is here
  HTTP_STATUS_CONTINUE = 100,
  ^
In file included from /wrkdirs/usr/ports/devel/opendht/work/opendht-3.1.11/src/dht_proxy_client.cpp:26:
/usr/local/include/http_parser.h:157:19: error: redefinition of enumerator 'HTTP_STATUS_SWITCHING_PROTOCOLS'
  HTTP_STATUS_MAP(XX)
                  ^
/usr/local/include/llhttp.h:191:3: note: previous definition is here
  HTTP_STATUS_SWITCHING_PROTOCOLS = 101,
  ^
```

```
/wrkdirs/usr/ports/devel/opendht/work/opendht-3.1.11/src/dht_proxy_server.cpp:119:9: error: no template named 'holds_alternative' in namespace 'restinio'; did you mean 'std::holds_alternative'?
    if (restinio::holds_alternative<restinio::connection_state::closed_t>(notice.cause())) {
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
        std::holds_alternative
/usr/include/c++/v1/variant:1502:16: note: 'std::holds_alternative' declared here
constexpr bool holds_alternative(const variant<_Types...>& __v) noexcept {
               ^
/wrkdirs/usr/ports/devel/opendht/work/opendht-3.1.11/src/dht_proxy_server.cpp:119:9: error: no template named 'holds_alternative' in namespace 'restinio'; did you mean 'std::holds_alternative'?
    if (restinio::holds_alternative<restinio::connection_state::closed_t>(notice.cause())) {
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
        std::holds_alternative
/usr/include/c++/v1/variant:1502:16: note: 'std::holds_alternative' declared here
constexpr bool holds_alternative(const variant<_Types...>& __v) noexcept {
               ^
2 errors generated.
```

Version: opendht-3.1.11
clang-18
FreeBSD 14.0

**Comment by aberaud** [comment]
We moved to llhttp, fixing the issue and compatibility with latest restinio versions.
Thanks for the report.
