### ISSUE TITLE
Debug Flag Causes Errors in the Header Files

### ISSUE THREAD

**Issue by naortega** [savoirfairelinux/opendht#329]
I'm working with OpenDHT `v1.7.4` (although I have tried this with versions `1.7.3` and `1.5.0`) on an ArchLinux machine (I received all my files from the repos). I'm using OpenDHT for a library and when I compiled I received the following error:
```
[ 50%] Building CXX object CMakeFiles/neocomm.dir/src/node.cpp.o
/usr/bin/clang++  -DDEBUG -DUNIX -I/home/nicolas/dev/C++/neocomm/include  -std=c++14 -Wall -Wextra -Wpedantic -Wfatal-errors -Werror -pedantic-errors -fno-elide-constructors -g -O0   -o CMakeFiles/neocomm.dir/src/node.cpp.o -c /home/nicolas/dev/C++/neocomm/src/node.cpp
In file included from /home/nicolas/dev/C++/neocomm/src/node.cpp:19:
In file included from /home/nicolas/dev/C++/neocomm/include/neocomm/node.hpp:21:
In file included from /home/nicolas/dev/C++/neocomm/include/neocomm/channel.hpp:23:
In file included from /usr/include/opendht.h:21:
In file included from /usr/include/opendht/dhtrunner.h:27:
/usr/include/opendht/log_enable.h:88:15: fatal error: expected member name or ';' after declaration specifiers
    LogMethod DEBUG = NOLOG;
    ~~~~~~~~~ ^
<command line>:1:15: note: expanded from here
#define DEBUG 1
              ^
1 error generated.
```
This error does not occur if I remove the `-DDEBUG` flag. It would be nice if these kinds of variable names were not used in header files for a library, as it can cause these issues. This kind of variable name is universally use for precompiler macros similar to how `NDEBUG` also is.

**Comment by aberaud** [comment]
Should be fixed by 00c1be9cdceebaf56b4829d78228372486355bac
