### ISSUE TITLE
opendht would not compile: no member named ‘on_work_started’ (boost v1.72)

### ISSUE THREAD

**Issue by meatshooter** [savoirfairelinux/opendht#520]
[ 83%] Building CXX object CMakeFiles/opendht.dir/src/dht_proxy_server.cpp.o
/usr/bin/x86_64-pc-linux-gnu-g++ -DASIO_STANDALONE -DOPENDHT_BUILD -DOPENDHT_JSONCPP -DOPENDHT_LOG=true -DOPENDHT_PEER_DISCOVERY -DOPENDHT_PROXY_CLIENT -DOPENDHT_PROXY_SERVER -DOPENDHT_PUSH_NOTIFICATIONS -DPACKAGE_VERSION=\"2.1.4\" -Dopendht_EXPORTS -I/var/tmp/portage/net-libs/opendht-9999/work/opendht-9999/. -I/var/tmp/portage/net-libs/opendht-9999/work/opendht-9999/include -I/var/tmp/portage/net-libs/opendht-9999/work/opendht-9999/include/opendht -I/var/tmp/portage/net-libs/opendht-9999/work/opendht-9999_build/include -isystem /usr/include/jsoncpp   -DNDEBUG -O2 -pipe -Wno-return-type -Wall -Wextra -Wnon-virtual-dtor -pedantic-errors -fvisibility=hidden -DMSGPACK_DISABLE_LEGACY_NIL -DMSGPACK_DISABLE_LEGACY_CONVERT -fPIC   -std=gnu++14 -o CMakeFiles/opendht.dir/src/dht_proxy_server.cpp.o -c /var/tmp/portage/net-libs/opendht-9999/work/opendht-9999/src/dht_proxy_server.cpp
In file included from /usr/include/asio/executor.hpp:340,
                 from /usr/include/asio.hpp:85,
                 from /usr/include/restinio/asio_include.hpp:14,
                 from /usr/include/restinio/impl/include_fmtlib.hpp:18,
                 from /usr/include/restinio/http_headers.hpp:11,
                 from /var/tmp/portage/net-libs/opendht-9999/work/opendht-9999/include/opendht/http.h:33,
                 from /var/tmp/portage/net-libs/opendht-9999/work/opendht-9999/include/opendht/dht_proxy_server.h:30,
                 from /var/tmp/portage/net-libs/opendht-9999/work/opendht-9999/src/dht_proxy_server.cpp:25:
/usr/include/asio/impl/executor.hpp: In instantiation of ‘void asio::executor::impl< <template-parameter-1-1>, <template-parameter-1-2> >::on_work_started() [with Executor = asio::execution::any_executor<asio::execution::context_as_t<asio::execution_context&>, asio::execution::detail::blocking::never_t<0>, asio::execution::prefer_only<asio::execution::detail::blocking::possibly_t<0> >, asio::execution::prefer_only<asio::execution::detail::outstanding_work::tracked_t<0> >, asio::execution::prefer_only<asio::execution::detail::outstanding_work::untracked_t<0> >, asio::execution::prefer_only<asio::execution::detail::relationship::fork_t<0> >, asio::execution::prefer_only<asio::execution::detail::relationship::continuation_t<0> > >; Allocator = std::allocator<void>]’:
/usr/include/asio/impl/executor.hpp:76:8:   required from here
/usr/include/asio/impl/executor.hpp:78:15: error: ‘class asio::execution::any_executor<asio::execution::context_as_t<asio::execution_context&>, asio::execution::detail::blocking::never_t<0>, asio::execution::prefer_only<asio::execution::detail::blocking::possibly_t<0> >, asio::execution::prefer_only<asio::execution::detail::outstanding_work::tracked_t<0> >, asio::execution::prefer_only<asio::execution::detail::outstanding_work::untracked_t<0> >, asio::execution::prefer_only<asio::execution::detail::relationship::fork_t<0> >, asio::execution::prefer_only<asio::execution::detail::relationship::continuation_t<0> > >’ has no member named ‘on_work_started’
   78 |     executor_.on_work_started();
      |     ~~~~~~~~~~^~~~~~~~~~~~~~~
/usr/include/asio/impl/executor.hpp: In instantiation of ‘void asio::executor::impl< <template-parameter-1-1>, <template-parameter-1-2> >::on_work_finished() [with Executor = asio::execution::any_executor<asio::execution::context_as_t<asio::execution_context&>, asio::execution::detail::blocking::never_t<0>, asio::execution::prefer_only<asio::execution::detail::blocking::possibly_t<0> >, asio::execution::prefer_only<asio::execution::detail::outstanding_work::tracked_t<0> >, asio::execution::prefer_only<asio::execution::detail::outstanding_work::untracked_t<0> >, asio::execution::prefer_only<asio::execution::detail::relationship::fork_t<0> >, asio::execution::prefer_only<asio::execution::detail::relationship::continuation_t<0> > >; Allocator = std::allocator<void>]’:
/usr/include/asio/impl/executor.hpp:81:8:   required from here
/usr/include/asio/impl/executor.hpp:83:15: error: ‘class asio::execution::any_executor<asio::execution::context_as_t<asio::execution_context&>, asio::execution::detail::blocking::never_t<0>, asio::execution::prefer_only<asio::execution::detail::blocking::possibly_t<0> >, asio::execution::prefer_only<asio::execution::detail::outstanding_work::tracked_t<0> >, asio::execution::prefer_only<asio::execution::detail::outstanding_work::untracked_t<0> >, asio::execution::prefer_only<asio::execution::detail::relationship::fork_t<0> >, asio::execution::prefer_only<asio::execution::detail::relationship::continuation_t<0> > >’ has no member named ‘on_work_finished’
   83 |     executor_.on_work_finished();
      |     ~~~~~~~~~~^~~~~~~~~~~~~~~~
/usr/include/asio/impl/executor.hpp: In instantiation of ‘void asio::executor::impl< <template-parameter-1-1>, <template-parameter-1-2> >::dispatch(asio::executor::function&&) [with Executor = asio::execution::any_executor<asio::execution::context_as_t<asio::execution_context&>, asio::execution::detail::blocking::never_t<0>, asio::execution::prefer_only<asio::execution::detail::blocking::possibly_t<0> >, asio::execution::prefer_only<asio::execution::detail::outstanding_work::tracked_t<0> >, asio::execution::prefer_only<asio::execution::detail::outstanding_work::untracked_t<0> >, asio::execution::prefer_only<asio::execution::detail::relationship::fork_t<0> >, asio::execution::prefer_only<asio::execution::detail::relationship::continuation_t<0> > >; Allocator = std::allocator<void>; asio::executor::function = asio::detail::executor_function]’:
/usr/include/asio/impl/executor.hpp:91:8:   required from here
/usr/include/asio/impl/executor.hpp:93:15: error: ‘class asio::execution::any_executor<asio::execution::context_as_t<asio::execution_context&>, asio::execution::detail::blocking::never_t<0>, asio::execution::prefer_only<asio::execution::detail::blocking::possibly_t<0> >, asio::execution::prefer_only<asio::execution::detail::outstanding_work::tracked_t<0> >, asio::execution::prefer_only<asio::execution::detail::outstanding_work::untracked_t<0> >, asio::execution::prefer_only<asio::execution::detail::relationship::fork_t<0> >, asio::execution::prefer_only<asio::execution::detail::relationship::continuation_t<0> > >’ has no member named ‘dispatch’
   93 |     executor_.dispatch(ASIO_MOVE_CAST(function)(f), allocator_);
      |     ~~~~~~~~~~^~~~~~~~
/usr/include/asio/impl/executor.hpp: In instantiation of ‘void asio::executor::impl< <template-parameter-1-1>, <template-parameter-1-2> >::post(asio::executor::function&&) [with Executor = asio::execution::any_executor<asio::execution::context_as_t<asio::execution_context&>, asio::execution::detail::blocking::never_t<0>, asio::execution::prefer_only<asio::execution::detail::blocking::possibly_t<0> >, asio::execution::prefer_only<asio::execution::detail::outstanding_work::tracked_t<0> >, asio::execution::prefer_only<asio::execution::detail::outstanding_work::untracked_t<0> >, asio::execution::prefer_only<asio::execution::detail::relationship::fork_t<0> >, asio::execution::prefer_only<asio::execution::detail::relationship::continuation_t<0> > >; Allocator = std::allocator<void>; asio::executor::function = asio::detail::executor_function]’:
/usr/include/asio/impl/executor.hpp:96:8:   required from here
/usr/include/asio/impl/executor.hpp:98:15: error: ‘class asio::execution::any_executor<asio::execution::context_as_t<asio::execution_context&>, asio::execution::detail::blocking::never_t<0>, asio::execution::prefer_only<asio::execution::detail::blocking::possibly_t<0> >, asio::execution::prefer_only<asio::execution::detail::outstanding_work::tracked_t<0> >, asio::execution::prefer_only<asio::execution::detail::outstanding_work::untracked_t<0> >, asio::execution::prefer_only<asio::execution::detail::relationship::fork_t<0> >, asio::execution::prefer_only<asio::execution::detail::relationship::continuation_t<0> > >’ has no member named ‘post’
   98 |     executor_.post(ASIO_MOVE_CAST(function)(f), allocator_);
      |     ~~~~~~~~~~^~~~
/usr/include/asio/impl/executor.hpp: In instantiation of ‘void asio::executor::impl< <template-parameter-1-1>, <template-parameter-1-2> >::defer(asio::executor::function&&) [with Executor = asio::execution::any_executor<asio::execution::context_as_t<asio::execution_context&>, asio::execution::detail::blocking::never_t<0>, asio::execution::prefer_only<asio::execution::detail::blocking::possibly_t<0> >, asio::execution::prefer_only<asio::execution::detail::outstanding_work::tracked_t<0> >, asio::execution::prefer_only<asio::execution::detail::outstanding_work::untracked_t<0> >, asio::execution::prefer_only<asio::execution::detail::relationship::fork_t<0> >, asio::execution::prefer_only<asio::execution::detail::relationship::continuation_t<0> > >; Allocator = std::allocator<void>; asio::executor::function = asio::detail::executor_function]’:
/usr/include/asio/impl/executor.hpp:101:8:   required from here
/usr/include/asio/impl/executor.hpp:103:15: error: ‘class asio::execution::any_executor<asio::execution::context_as_t<asio::execution_context&>, asio::execution::detail::blocking::never_t<0>, asio::execution::prefer_only<asio::execution::detail::blocking::possibly_t<0> >, asio::execution::prefer_only<asio::execution::detail::outstanding_work::tracked_t<0> >, 
It seems that opendht would not compile with boost 1.72:

asio::execution::prefer_only<asio::execution::detail::outstanding_work::untracked_t<0> >, asio::execution::prefer_only<asio::execution::detail::relationship::fork_t<0> >, asio::execution::prefer_only<asio::execution::detail::relationship::continuation_t<0> > >’ has no member named ‘defer’; did you mean ‘prefer’?
  103 |     executor_.defer(ASIO_MOVE_CAST(function)(f), allocator_);
      |     ~~~~~~~~~~^~~~~
      |     prefer
make[2]: *** [CMakeFiles/opendht.dir/build.make:310: CMakeFiles/opendht.dir/src/dht_proxy_server.cpp.o] Error 1
make[2]: Leaving directory '/var/tmp/portage/net-libs/opendht-9999/work/opendht-9999_build'
make[1]: *** [CMakeFiles/Makefile2:96: CMakeFiles/opendht.dir/all] Error 2
make[1]: Leaving directory '/var/tmp/portage/net-libs/opendht-9999/work/opendht-9999_build'
make: *** [Makefile:130: all] Error 2

**Comment by aberaud** [comment]
Was probably related to boost version
